### ISSUE TITLE
'typedef' ignored in declaration SparkFunMLX90614.h

### ISSUE THREAD

**Issue by lvZandbrink** [sparkfun/SparkFun_MLX90614_Arduino_Library#1]
Hello Sparkfun,

I am just starting with Arduino and I have problems verifying the MLX_Get_ID code. It refers to SparkFun_MLX90614_Arduino_Library/src/SparkFunMLX90614.h and gives the following warning:

In file included from ...\Arduino\libraries\SparkFun_MLX90614_Arduino_Library-master\examples\MLX90614_Get_ID\MLX90614_Get_ID.ino:25:0:

...\Arduino\libraries\SparkFun_MLX90614_Arduino_Library-master\src/SparkFunMLX90614.h:54:1: warning: 'typedef' was ignored in this declaration [enabled by default]

 };

 ^

So, this example didn't work out for me, as well as the other three examples.

What is it that I am doing wrong?

Luc

**Comment by BurgerDan** [comment]
I'm having the same problem, from what I was able to narrow down: The: typedef ernum wasn't done correctly. At least based on C++ it wasn't. It looks like the name of the enumerator need to go between the } and the ; so it would look like:
typedef enum{
banana1
banana2
banana3
}banana_num;
That's what I could find, I might be looking at the wrong thing though.

**Comment by Resonanz** [comment]
Same same.

**Comment by nseidle** [comment]
Hi folks - I am attempting to replicate using an Uno under Arduino 1.8.7 but cannot. Perhaps the compiler has changed slightly since first issue report but the GetID example compiles fine for me. Regardless, I've moved the declarator after the enum brackets (better practice). Should be fixed in v1.0.2. Please re-open if you continue to have issues.
